import json
import tarfile
import tempfile
import unittest
from pathlib import Path

from md_automation.charmm_gui_gromacs import (
    continue_pipeline,
    setup_pipeline,
)
from md_automation.cluster_config import ClusterConfig
from md_automation.discovery import (
    DiscoveryError,
    _safe_extract,
    discover_workflow,
    find_engine_dir,
)
from md_automation.readme_parse import parse_readme


STANDARD_README = """#!/bin/csh
# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

set init = step5_input
set rest_prefix = step5_input
set mini_prefix = step6.0_minimization
set equi_prefix = step6.%d_equilibration
set prod_prefix = step7_production

# Minimization
gmx grompp -f ${mini_prefix}.mdp

# Equilibration
set cnt    = 1
set cntmax = 6
while ( ${cnt} <= ${cntmax} )
end
"""

ASSEMBLER_README = """#!/bin/csh
# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

set init = step5_input
set rest_prefix = step5_input
set mini_prefix = step6.0_minimization
set equi_prefix = step6.%d_equilibration
set prod_prefix = step7_production
set prod_step   = step7

# Minimization
gmx_d mdrun -v -deffnm ${mini_prefix}

# Equilibration
set cnt    = 1
set cntmax = 6
while ( ${cnt} <= ${cntmax} )
end

# Production
set cnt    = 1
set cntmax = 10
while ( ${cnt} <= ${cntmax} )
end
"""


def _write_engine_files(gromacs_dir: Path, equi_steps: int = 6) -> None:
    gromacs_dir.mkdir(parents=True, exist_ok=True)
    (gromacs_dir / "topol.top").write_text("; topology\n", encoding="utf-8")
    (gromacs_dir / "index.ndx").write_text("[ System ]\n", encoding="utf-8")
    (gromacs_dir / "step5_input.gro").write_text("gro\n", encoding="utf-8")
    (gromacs_dir / "step5_input.pdb").write_text("pdb\n", encoding="utf-8")
    (gromacs_dir / "step6.0_minimization.mdp").write_text("integrator = steep\n", encoding="utf-8")
    for i in range(1, equi_steps + 1):
        (gromacs_dir / f"step6.{i}_equilibration.mdp").write_text("integrator = md\n", encoding="utf-8")
    (gromacs_dir / "step7_production.mdp").write_text("integrator = md\n", encoding="utf-8")


def make_export(root: Path, layout: str = "assembler", equi_steps: int = 6) -> Path:
    """Build a synthetic export tree; returns the archive root directory."""
    base = root / "charmm-gui-1234567890"
    gromacs = base / "gromacs"
    _write_engine_files(gromacs, equi_steps)
    if layout == "assembler":
        (base / "input.config.dat").write_text(
            json.dumps({"systype": "bilayer", "input": ["namd", "gromacs"]}), encoding="utf-8"
        )
        (gromacs / "README").write_text(ASSEMBLER_README, encoding="utf-8")
        (base / "namd").mkdir()
        (base / "namd" / "README").write_text("#!/bin/csh\n", encoding="utf-8")
    else:
        (base / "README").write_text(STANDARD_README, encoding="utf-8")
    return base


def make_archive(root: Path, layout: str = "assembler", equi_steps: int = 6) -> Path:
    base = make_export(root, layout, equi_steps)
    archive = root / "export.tgz"
    with tarfile.open(archive, "w:gz") as tar:
        tar.add(base, arcname=base.name)
    return archive


class ReadmeParseTests(unittest.TestCase):
    def test_assembler_readme_scoped_cntmax(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            readme = Path(directory) / "README"
            readme.write_text(ASSEMBLER_README, encoding="utf-8")
            info = parse_readme(readme)
        self.assertEqual(info.equi_cntmax, 6)
        self.assertEqual(info.prod_cntmax, 10)
        self.assertEqual(info.prod_step, "step7")
        self.assertEqual(info.equi_prefix, "step6.%d_equilibration")

    def test_standard_readme(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            readme = Path(directory) / "README"
            readme.write_text(STANDARD_README, encoding="utf-8")
            info = parse_readme(readme)
        self.assertEqual(info.equi_cntmax, 6)
        self.assertIsNone(info.prod_cntmax)
        self.assertIsNone(info.prod_step)


class DiscoveryTests(unittest.TestCase):
    def test_assembler_layout(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            base = make_export(Path(directory), "assembler")
            layout = find_engine_dir(base.parent)
        self.assertEqual(layout.kind, "assembler")
        self.assertEqual(layout.engine_dir.name, "gromacs")
        self.assertEqual(layout.readme.name, "README")
        self.assertEqual(layout.readme.parent.name, "gromacs")

    def test_standard_layout(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            base = make_export(Path(directory), "standard")
            layout = find_engine_dir(base)
        self.assertEqual(layout.kind, "standard")
        self.assertEqual(layout.readme.parent, base)

    def test_namd_only_fails_loudly(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory) / "charmm-gui-1"
            (base / "namd").mkdir(parents=True)
            (base / "namd" / "step7_production.inp").write_text("x", encoding="utf-8")
            with self.assertRaisesRegex(DiscoveryError, "NAMD-only"):
                find_engine_dir(base)

    def test_reader_only_fails_loudly(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory) / "charmm-gui-2"
            base.mkdir()
            (base / "step1_pdbreader.psf").write_text("x", encoding="utf-8")
            with self.assertRaisesRegex(DiscoveryError, "PDB-reader"):
                find_engine_dir(base)

    def test_discover_workflow_counts_files_not_cntmax(self) -> None:
        """An assembler README says cntmax=6; only 3 mdps -> 3 steps."""
        with tempfile.TemporaryDirectory() as directory:
            base = make_export(Path(directory), "assembler", equi_steps=3)
            layout = find_engine_dir(base)
            info = parse_readme(layout.readme)
            config = discover_workflow(layout, info)
        self.assertEqual(config.equilibration_steps, 3)
        self.assertEqual(config.equi_mdps[-1], "step6.3_equilibration")
        self.assertEqual(config.prod_step, "step7")

    def test_safe_extract_rejects_path_traversal(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            archive = root / "unsafe.tgz"
            with tarfile.open(archive, "w:gz") as tar:
                member = tarfile.TarInfo("../../outside.txt")
                member.size = 0
                tar.addfile(member)
            with self.assertRaises(ValueError):
                _safe_extract(archive, root / "extract")


class PipelineTests(unittest.TestCase):
    def _build(self, tmp: Path, layout="assembler", **kwargs) -> Path:
        archive = make_archive(tmp, layout)
        return setup_pipeline(archive, "sim", cluster=ClusterConfig(), **kwargs)

    def test_build_assembler_archive(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out = self._build(Path(directory), output_dir=Path(directory) / "out")
            self.assertTrue((out / "submit_all.sh").is_file())
            self.assertTrue((out / "preflight.sh").is_file())
            self.assertTrue((out / "pipeline_manifest.json").is_file())
            self.assertTrue((out / "minimization" / "gmx_step6.0_minimization.sh").is_file())
            self.assertTrue((out / "production" / "gmx_step7_production.sh").is_file())

            submit = (out / "submit_all.sh").read_text(encoding="utf-8")
            self.assertIn("--dependency=afterok:", submit)

            job = (out / "minimization" / "gmx_step6.0_minimization.sh").read_text(encoding="utf-8")
            self.assertIn("#SBATCH", job)
            self.assertIn(".done_step6.0_minimization", job)
            self.assertIn("already finished", job)

            manifest = json.loads((out / "pipeline_manifest.json").read_text(encoding="utf-8"))
            self.assertEqual(manifest["source"]["layout"], "assembler")
            self.assertEqual(manifest["workflow"]["prod_step"], "step7")

    def test_prod_chunks_chain_checkpoints(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out = self._build(
                Path(directory), prod_chunks=3, output_dir=Path(directory) / "out"
            )
            for i in (1, 2, 3):
                self.assertTrue((out / "production" / f"gmx_step7_{i}.sh").is_file())
            chunk2 = (out / "production" / "gmx_step7_2.sh").read_text(encoding="utf-8")
            self.assertIn("-c step7_1.gro -t step7_1.cpt", chunk2)
            manifest = json.loads((out / "pipeline_manifest.json").read_text(encoding="utf-8"))
            self.assertEqual(manifest["workflow"]["prod_chunks"], 3)

    def test_directory_input(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            base = make_export(Path(directory), "assembler")
            out = setup_pipeline(
                base, "sim", cluster=ClusterConfig(),
                output_dir=Path(directory) / "out",
            )
            self.assertTrue((out / "submit_all.sh").is_file())

    def test_dry_run_writes_nothing(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            archive = make_archive(Path(directory))
            output = Path(directory) / "out"
            result = setup_pipeline(
                archive, "sim", cluster=ClusterConfig(), dry_run=True, output_dir=output
            )
            self.assertIsNone(result)
            self.assertFalse(output.exists())

    def test_bash_scheduler_writes_run_all(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            cluster = ClusterConfig(scheduler="bash")
            out = setup_pipeline(
                make_archive(Path(directory)), "sim",
                cluster=cluster, output_dir=Path(directory) / "out",
            )
            self.assertTrue((out / "run_all.sh").is_file())
            self.assertFalse((out / "submit_all.sh").exists())
            job = (out / "minimization" / "gmx_step6.0_minimization.sh").read_text(encoding="utf-8")
            self.assertNotIn("#SBATCH", job)
            self.assertIn(".done_step6.0_minimization", job)

    def test_continue_pipeline_appends_chunks(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            out = self._build(
                Path(directory), prod_chunks=2, output_dir=Path(directory) / "out"
            )
            continue_pipeline(out, 2)
            chunk4 = (out / "production" / "gmx_step7_4.sh").read_text(encoding="utf-8")
            self.assertIn("-c step7_3.gro -t step7_3.cpt", chunk4)
            self.assertTrue((out / "submit_continue.sh").is_file())

    def test_force_replaces_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            archive = make_archive(Path(directory))
            out = Path(directory) / "out"
            setup_pipeline(archive, "sim", cluster=ClusterConfig(), output_dir=out)
            with self.assertRaises(FileExistsError):
                setup_pipeline(archive, "sim", cluster=ClusterConfig(), output_dir=out)
            setup_pipeline(archive, "sim", cluster=ClusterConfig(), output_dir=out, force=True)


if __name__ == "__main__":
    unittest.main()
